### ISSUE TITLE
[Improvement] Xbox 360 shaders for NFS MW rearview mirror

### ISSUE THREAD

**Issue by Scar557** [AeroWidescreen/NFSMWHDReflections#2]
Since osdever's mod isn't even finished, it's maybe a bit dumb, but i had an idea, what about adding to the next update a full implementation of the Xbox 360 shaders in NFSMWHDReflections and also adding that to the rear view mirror ... ?

Since you implemented the original shaders to the game rear-view mirror, and you worked with osdever in the 1.2 update, well, it shouldn't be that hard, right ... ?

**Comment by AeroWidescreen** [comment]
> full implementation of the Xbox 360 shaders in NFSMWHDReflections

The 360 shaders is a completely different project with different goals, priorities, and problems. There is no reason for it to be merged.

> Since you implemented the original shaders to the game rear-view mirror, and you worked with osdever in the 1.2 update, well, it shouldn't be that hard, right ... ?

The shaders for the mirror were simply switched on, meaning its behavior is now identical to the rest of the game. Any changes made to the shaders should be applied automatically, no additional work needed.
