### ISSUE TITLE
extra brightness in mirror

### ISSUE THREAD

**Issue by vjadid** [AeroWidescreen/NFSMWHDReflections#4]
Not sure if I'm doing something wrong but everything in rearview mirror appears extra bright.
I'm using the latest asi, and I checked without any other asi. Attaching the relevant screenshots.

![front 1](https://user-images.githubusercontent.com/29530546/63648729-8f2ed400-c751-11e9-8b96-1e288ce1f955.jpg)
![back 1](https://user-images.githubusercontent.com/29530546/63648727-8e963d80-c751-11e9-8ad0-c15a00eeb50d.jpg)
![front 2](https://user-images.githubusercontent.com/29530546/63648730-8f2ed400-c751-11e9-9467-ab691fe4fa35.jpg)
![back 2](https://user-images.githubusercontent.com/29530546/63648728-8e963d80-c751-11e9-8e91-65516ee6570e.jpg)
![front 3](https://user-images.githubusercontent.com/29530546/63648731-8fc76a80-c751-11e9-92bc-758d1877e4c7.jpg)
![ini settings](https://user-images.githubusercontent.com/29530546/63648732-8fc76a80-c751-11e9-9e23-9b8b21351d6f.png)
![loaded asi](https://user-images.githubusercontent.com/29530546/63648733-8fc76a80-c751-11e9-9730-7032c330d688.png)

**Comment by AeroWidescreen** [comment]
Try disabling MirrorTint or adjust the RGB values to decrease the brightness. For example:

> MirrorTintR = 200
> MirrorTintG = 200
> MirrorTintB = 200

**Comment by vjadid** [comment]
Ok so disabling MirrorTint did not fix the issue (I keep Visual treatment off in Video settings if that is relevant).
![mirror tint 0](https://user-images.githubusercontent.com/29530546/63665406-d025f780-c7e8-11e9-962e-2a09974bcc23.png)

Adjusting RGB values fixed the issue. Is it possible that mirror brightness be set in the asi to brightness of world by default?
Also I'm not sure if this is expected but I cannot see tree shadows in mirror.
![no shadows front](https://user-images.githubusercontent.com/29530546/63665546-60fcd300-c7e9-11e9-8d62-5c48c57aa41b.png)
![no shadows](https://user-images.githubusercontent.com/29530546/63665548-6823e100-c7e9-11e9-9efc-6dc1dc578b48.png)

**Comment by vjadid** [comment]
Closing the issue.
Adjusting the MirrorTint RGB values decreased the brightness in the rearview mirror (used 150 for each)

![fixed mirror brightness](https://user-images.githubusercontent.com/29530546/63823547-dbf0f580-c971-11e9-93df-2b12832f84bc.PNG)

**Comment by AeroWidescreen** [comment]
Thank you, I'll change the default RGB value in the next update.
