### ISSUE TITLE
How do I even install this mod?

### ISSUE THREAD

**Issue by Diamondew** [AeroWidescreen/NFSMWHDReflections#6]
Sorry for the super dumb question... Thought that it's a simple drag and place into the "scripts" folder

**Comment by AeroWidescreen** [comment]
>Thought that it's a simple drag and place into the "scripts" folder

It is. Is there something about these steps that are confusing you?

1. Download and extract **NFSMWHDReflections.zip**.
2. Move the *scripts* folder to the game's installation folder, where the executable is located.
3. Download and extract [Ultimate-ASI-Loader.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases).
4. Move *dinput8.dll* to the game's installation folder, where the executable is located.
