### ISSUE TITLE
Parked cars don't render unless damaged

### ISSUE THREAD

**Issue by vjadid** [AeroWidescreen/NFSMWHDReflections#7]
See before(release 1.2.5) and after (release 1.3.0)

![Screenshot (21)](https://user-images.githubusercontent.com/29530546/66758014-0c0d3d00-eebb-11e9-88aa-23fc08e0e31b.png)
![Screenshot (22)](https://user-images.githubusercontent.com/29530546/66758091-3828be00-eebb-11e9-805d-7b33b1853109.png)
![Screenshot (23)](https://user-images.githubusercontent.com/29530546/66758097-3b23ae80-eebb-11e9-9049-47363ac4024c.png)
![Screenshot (24)](https://user-images.githubusercontent.com/29530546/66758102-3d860880-eebb-11e9-8b4a-5f27fc27bbbc.png)

**Comment by AeroWidescreen** [comment]
Could you tell me if this works for you?

[Download](https://mega.nz/#!0DQTWKxR!aeuJkwCXZ0ELEuCNMM1k4cm5xm6LO6GygazaB9zAjak)

**Comment by vjadid** [comment]
> 
> 
> Could you tell me if this works for you?
> 
> [Download](https://mega.nz/#!0DQTWKxR!aeuJkwCXZ0ELEuCNMM1k4cm5xm6LO6GygazaB9zAjak)

Works perfectly, its so awesome man.

**Comment by AeroWidescreen** [comment]
Okay, thanks. I should have an update out for this later today.

**Comment by AeroWidescreen** [comment]
Update is released.
