### ISSUE TITLE
v1.3 .exe Error

### ISSUE THREAD

**Issue by AlexKVideos1** [AeroWidescreen/NFSMWHDReflections#8]
I'm having an issue where the mod claims that I'm not using the v1.3 English .exe of the NFS MW, however I've verified that I've updated to v1.3, by checking the version number in the bottom right when the game starts. My game version is the US Black Box Edition, and the patch was downloaded from [PCGamingWiki](https://community.pcgamingwiki.com/files/file/1066-need-for-speed-most-wanted-patch/).

Not sure what the issue is so I wanted to bring it up.

**Comment by AeroWidescreen** [comment]
It requires a No-CD patch, such as v1.3 RELOADED speed.exe. 

You can get that here. Scroll down to the installation section and you should find a download a link: https://github.com/ExOptsTeam/NFSMWExOpts/wiki/Getting-Started#installation

**Comment by AlexKVideos1** [comment]
> It requires a No-CD patch, such as v1.3 RELOADED speed.exe.
> 
> You can get that here, towards the beginning of the installation section: https://github.com/ExOptsTeam/NFSMWExOpts/wiki/Getting-Started#installation

Thank you. I wasn't sure if I needed a crack or not. That should be made clear for others just to avoid confusion. NFS MW is the only old NFS game that worked on Windows 10 without a crack for me.
